# Generated by Django 5.1.4 on 2024-12-21 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_remove_exam_test_examresult_exam_exam_results'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='pin',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
