# Generated by Django 5.1.4 on 2024-12-21 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_alter_employee_pin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examresult',
            name='exam',
        ),
    ]
