# Generated by Django 5.1.4 on 2024-12-22 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0005_remove_exam_exam_results_examresult_exam_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examresult',
            name='selected_option_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='examresult',
            unique_together={('exam', 'test')},
        ),
    ]
