# Generated by Django 5.1.4 on 2024-12-22 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0006_examresult_selected_option_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='examresult',
            old_name='selected_option_number',
            new_name='selected_option_index',
        ),
    ]
