# Generated by Django 5.1.4 on 2024-12-22 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0007_rename_selected_option_number_examresult_selected_option_index'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='correct_answer',
            new_name='correct_option',
        ),
        migrations.RemoveField(
            model_name='test',
            name='option4',
        ),
    ]
