# Generated by Django 5.0.7 on 2025-01-03 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0008_rename_correct_answer_test_correct_option_and_more'),
        ('profiles', '0004_profile_pin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='overseer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overseer', to='profiles.profile'),
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
