# Generated by Django 5.0.7 on 2025-01-04 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0009_alter_exam_employee_alter_exam_overseer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='timer',
            field=models.PositiveIntegerField(default=20),
        ),
    ]
