# Generated by Django 5.0.7 on 2025-01-05 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0010_exam_timer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exam',
            old_name='timer',
            new_name='time_limit',
        ),
    ]
