# Generated by Django 5.0.7 on 2025-01-05 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0011_rename_timer_exam_time_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='started',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
