# Generated by Django 5.0.7 on 2025-01-06 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0012_exam_started'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='pdf_id',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exam',
            name='pdf_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
