# Generated by Django 5.0.7 on 2025-01-06 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0013_exam_pdf_id_exam_pdf_path'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exam',
            old_name='pdf_id',
            new_name='unique_id',
        ),
    ]
