# Generated by Django 5.0.7 on 2025-01-12 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0014_rename_pdf_id_exam_unique_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
