# Generated by Django 5.0.7 on 2025-01-12 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0015_exam_deadline'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exam',
            old_name='pdf_path',
            new_name='pdf_short_path',
        ),
    ]
