# Generated by Django 5.0.7 on 2025-01-03 16:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='full_name',
            new_name='fullname',
        ),
        migrations.AddField(
            model_name='profile',
            name='position',
            field=models.CharField(default='dasturchi', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='seniority_railway',
            field=models.DateField(default=datetime.datetime(2025, 1, 3, 16, 35, 18, 76795, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='tabel_num',
            field=models.CharField(default=35866, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
