# Generated by Django 5.0.7 on 2025-01-03 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_rename_full_name_profile_fullname_profile_position_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='seniority_position',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='seniority_railway',
            field=models.DateField(blank=True, null=True),
        ),
    ]
