# Generated by Django 5.0.7 on 2025-01-03 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_profile_seniority_position_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='pin',
            field=models.CharField(default=51810016980034, max_length=20),
            preserve_default=False,
        ),
    ]
