# Generated by Django 5.1.5 on 2025-01-15 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_role_description_alter_profile_tabel_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='employment_record_pdf_path',
            field=models.FilePathField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='med_card_pdf_path',
            field=models.FilePathField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='passport_pdf_path',
            field=models.FilePathField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='recommendation_pdf_path',
            field=models.FilePathField(blank=True, null=True),
        ),
    ]
