# Generated by Django 5.1.5 on 2025-01-15 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_profile_employment_record_pdf_path_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='employment_record_pdf_path',
            field=models.FilePathField(blank=True, match='.*\\.pdf$', null=True, path='files/documents'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='med_card_pdf_path',
            field=models.FilePathField(blank=True, match='.*\\.pdf$', null=True, path='files/documents'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='passport_pdf_path',
            field=models.FilePathField(blank=True, match='.*\\.pdf$', null=True, path='files/documents'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='recommendation_pdf_path',
            field=models.FilePathField(blank=True, match='.*\\.pdf$', null=True, path='files/documents'),
        ),
    ]
