# Generated by Django 5.1.5 on 2025-01-15 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_company_alter_profile_employment_record_pdf_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='profiles.company'),
            preserve_default=False,
        ),
    ]
