# Generated by Django 5.1.5 on 2025-01-15 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_profile_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocomotiveCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile')),
                ('locomotive_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.locomotivecategory')),
            ],
        ),
    ]
