# Generated by Django 5.1.5 on 2025-01-15 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_locomotivecategory_application'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='employment_record_pdf_path',
            new_name='work_record_pdf_path',
        ),
    ]
