# Generated by Django 5.1.5 on 2025-01-15 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0012_rename_employment_record_pdf_path_profile_work_record_pdf_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='med_card_pdf_path',
            field=models.FilePathField(blank=True, match='.*\\.pdf$', null=True, path='files\\documents'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='passport_pdf_path',
            field=models.FilePathField(blank=True, match='.*\\.pdf$', null=True, path='files\\documents'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='recommendation_pdf_path',
            field=models.FilePathField(blank=True, match='.*\\.pdf$', null=True, path='files\\documents'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='work_record_pdf_path',
            field=models.FilePathField(blank=True, match='.*\\.pdf$', null=True, path='files\\documents'),
        ),
    ]
