# Generated by Django 5.1.5 on 2025-01-15 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0013_alter_profile_med_card_pdf_path_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='med_card_pdf_path',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='passport_pdf_path',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='recommendation_pdf_path',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='work_record_pdf_path',
        ),
        migrations.AddField(
            model_name='profile',
            name='med_card_pdf',
            field=models.FileField(blank=True, null=True, upload_to='files\\documents'),
        ),
        migrations.AddField(
            model_name='profile',
            name='passport_pdf',
            field=models.FileField(blank=True, null=True, upload_to='files\\documents'),
        ),
        migrations.AddField(
            model_name='profile',
            name='recommendation_pdf',
            field=models.FileField(blank=True, null=True, upload_to='files\\documents'),
        ),
        migrations.AddField(
            model_name='profile',
            name='work_record_pdf',
            field=models.FileField(blank=True, null=True, upload_to='files\\documents'),
        ),
    ]
