# Generated by Django 5.1.5 on 2025-01-15 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0014_remove_profile_med_card_pdf_path_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='med_card_pdf',
            field=models.FileField(blank=True, null=True, upload_to='documents'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='passport_pdf',
            field=models.FileField(blank=True, null=True, upload_to='documents'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='recommendation_pdf',
            field=models.FileField(blank=True, null=True, upload_to='documents'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='work_record_pdf',
            field=models.FileField(blank=True, null=True, upload_to='documents'),
        ),
    ]
