# Generated by Django 5.1.5 on 2025-01-17 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0017_alter_settings_value'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LocomotiveCategory',
            new_name='CourseCategory',
        ),
    ]
