# Generated by Django 5.1.5 on 2025-01-17 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0018_rename_locomotivecategory_coursecategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecategory',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
