# Generated by Django 5.1.5 on 2025-01-17 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0019_coursecategory_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('docs_preparing', 'Hujjatlar tayyorlanmoqda'), ('ready_to_send', 'Taqdim qilishga tayyor'), ('under_review', 'Yuborilgan'), ('approved', 'Tasdiqlangan'), ('returned', 'Qayta ishlashga yuborilgan')], default='docs_preparing', max_length=255),
        ),
    ]
