# Generated by Django 5.1.5 on 2025-01-17 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0020_application_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='locomotive_category',
            new_name='curse_category',
        ),
    ]
