# Generated by Django 5.1.5 on 2025-01-27 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0021_rename_locomotive_category_application_curse_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('docs_preparing', 'Hujjatlar tayyorlanmoqda'), ('ready_to_send', 'Taqdim qilishga tayyor'), ('under_review', "Ko'rib chiqishga yuborilgan"), ('ready_to_exam', 'Imtihon topshirish mumkin'), ('confirmation', 'Tasdiqlashda'), ('approved', 'Tasdiqlangan'), ('returned', 'Qayta ishlashga yuborilgan')], default='docs_preparing', max_length=255),
        ),
    ]
